[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Dinosaur_Venture"
version = "0.1.0"
description = "Journey through several places, gathering new cards and meeting new enemies all throughout"