[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# For running pytest correctly
[tool.pytest.ini_options]
pythonpath = ["src"]

[project]
name = "Dinosaur_Venture"
version = "0.1.0"
description = "Journey through several places, gathering new cards and meeting new enemies all throughout"
dependencies = [
    "colorama>=0.4.6",
    "pytest>=8.4.2",
    "pytest-timeout>=2.4.0",
    "send2trash>=1.8.3",
    "flask>=3.1.2",
    "ansi2html>=1.9.2",
    "zappa>=0.61.4",
    "flask-cors>=6.0.2"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]