name: Deploy Cards Service

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - react-frontend
    paths:
      - 'web_app/entities_service.py'
      - 'src/Dinosaur_Venture/**'

jobs:
  deploy:
    uses: ./.github/workflows/deploy_backend_template.yml
    with:
      zappa_stage: dev