name: Deploy Backend Template

on:
  workflow_call:
    inputs:
      zappa_stage:
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::766766277102:role/GitHubActionsLambdaDeploy
          aws-region: us-east-1

      - name: Creating and activating virtual environment
        run: python -m venv venv

      - name: Install project and dependencies
        run: |
          source venv/bin/activate
          pip install .

      - name: Deploy with Zappa
        run: |
          source venv/bin/activate
          zappa update ${{ inputs.zappa_stage }}
