name: Run Pytest

on:
  push:
  pull_request:

jobs:
  run_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Runs PyTest
        uses: ./.github/workflows/pytest.yml